### PR TITLE
JSON::Validator 3 changes

### LINKED ISSUE #44: JSON::Validator::OpenAPI was removed
See https://metacpan.org/changes/distribution/JSON-Validator#L14 (FYI: @jhthorsen)

This means Yancy's test suite currently fails:
```
#   Failed test 'Mojolicious/Plugin/Yancy.pm loaded ok'
#   at t/00-compile.t line 53.
#          got: '512'
#     expected: '0'
Can't locate JSON/Validator/OpenAPI.pm in @INC (you may need to install the JSON::Validator::OpenAPI module) (@INC contains: ... .) at /home/cpansand/.cpan/build/2019010609/Yancy-1.020-1/blib/lib/Mojolicious/Plugin/Yancy.pm line 408.
BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2019010609/Yancy-1.020-1/blib/lib/Mojolicious/Plugin/Yancy.pm line 408.
Compilation failed in require at -e line 1.
# Looks like you failed 1 test of 10.
t/00-compile.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/10 subtests 
	(less 1 skipped subtest: 8 okay)
... (etc)...
```

### PR DESCRIPTION
**Pull request by mohawk2**
`JSON::Validator::OpenAPI` is gone, use `JSON::Validator::OpenAPI::Mojolicious`

format functions must return `undef` when ok

Coerce to real JSON booleans, not 'true'/'false' as JV fixed a bug. Previously coercion did not coerce ie mutate the passed-in values, now it does and it doesn't recognise the strings as boolean values.

Also update the deps, and eliminate a surprising duplicate `blog` spec in `t/helpers.t`.

Fixes #44.

### CODE REVIEW

**Comment by mohawk2** [comment]
The extra commit makes sense to me, and is similar to what I tried. Yes, agreed with the Devel::Hide thing. Are you happy to do that or should I?

**Comment by preaction** [comment]
No, I'm wrong: We would need a test _with_ Cpanel::JSON::XS, since Mojo::JSON prefers it in cases where it exists. The 5.14 test was failing _without_ Cpanel::JSON::XS, which made it fall back to Mojo::JSON and JSON::PP::Boolean booleans... Either way, that's not important for this. Let's ship it!

**Comment by preaction** [comment]
... and Mojo::JSON always uses JSON::PP::true and JSON::PP::false... Curiouser and curiouser...

**Comment by mohawk2** [comment]
This was caused by https://github.com/mojolicious/json-validator/issues/145

**Pull request merged**
